openapi: 3.0.0
info:
  title: "LINGO Server"
  description: "API for the LINGO project"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Word:
      type: "object"
      required:
        - word
      properties:
        id:
          type: "string"
        word:
          type: "string"
    Meaning:
      type: "object"
      required:
        - meaning
      properties:
        id:
          type: "string"
        meaning:
          type: "string"
    Reflection:
      type: "object"
      required:
        - reflection
      properties:
        id:
          type: "string"
        reflection:
          type: "string"
    User:
      type: "object"
      required:
        - first_name
        - last_name
        - email
        - created_on
        - modified_on
      properties:
        first_name:
          type: "string"
        last_name:
          type: "string"
        created_on:
          type: "string"
        modified_on:
          type: "string"
    Project:
      type: "object"
      required:
        - oroject_name
        - project_owner
        - is_active
        - created_on
        - modified_on
      properties:
        project_name:
          type: "string"
        project_owner:
          type: "string"
        is_active:
          type: "string"
        created_on:
          type: "string"
        modified_on:
          type: "string"
paths:
  /users:
    get:
      operationId: "users.get_all"
      tags:
        - "Users"
      summary: "Return the list of users"
      responses:
        "200":
          description: "Successfully read list of users"
  /users/{id}:
    get:
      operationId: "users.get"
      tags:
        - "Users"
      summary: "Return an individual user by id"
      responses:
        "200":
          description: "Successfully retrieved user"
  /projects:
    get:
      operationId: "projects.get_all"
      tags:
        - "Projects"
      summary: "Return the list of projects"
      responses:
        "200":
          description: "Successfully read list of projects"
  /projects/{id}:
    get:
      operationId: "projects.get"
      tags:
        - "Projects"
      summary: "Return an individual project by id"
      responses:
        "200":
          description: "Successfully retrieved project"
  /words:
    get:
      operationId: "words.get_all"
      tags:
        - "Words"
      summary: "Return the list of words"
      responses:
        "200":
          description: "Successfully read list of words"
    post:
      operationId: "words.create"
      tags:
        - "Words"
      summary: "Create a new word"
      requestBody:
        description: "Word to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "word"
              $ref: "#/components/schemas/Word"
      responses:
        "200":
          description: "Successfully created word"
  /words/{id}:
    get:
      operationId: "words.get"
      tags:
        - "Words"
      summary: "Return an individual word by id"
      responses:
        "200":
          description: "Successfully retrieved word"
    put:
      operationId: "words.update"
      tags:
        - "Words"
      summary: "Update an existing word"
      requestBody:
        description: "Word to update"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "word"
              $ref: "#/components/schemas/Word"
      responses:
        "200":
          description: "Successfully updated word"
  /words/{word_id}/meanings:
    get:
      operationId: "meanings.get_all"
      tags:
        - "Meanings"
      summary: "Return the list of meanings for a word"
      responses:
        "200":
          description: "Successfully read list of meanings"
    post:
      operationId: "meanings.create"
      tags:
        - "Meanings"
      summary: "Create a new meaning for a word"
      requestBody:
        description: "Meaning to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "meaning"
              $ref: "#/components/schemas/Meaning"
      responses:
        "200":
          description: "Successfully created meaning for word"
  /words/{word_id}/meanings/{id}:
    get:
      operationId: "meanings.get"
      tags:
        - "Meanings"
      summary: "Return an individual meaning by id"
      responses:
        "200":
          description: "Successfully retrieved meaning"
    put:
      operationId: "meanings.update"
      tags:
        - "Meanings"
      summary: "Update an existing meaning"
      requestBody:
        description: "Meaning to update"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "meaning"
              $ref: "#/components/schemas/Meaning"
      responses:
        "200":
          description: "Successfully updated meaning"
