openapi: 3.0.0
info:
  title: "LINGO Server"
  description: "API for the LINGO project"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Word:
      type: "object"
      required:
        - word
      properties:
        id:
          type: "integer"
        word:
          type: "string"
        active:
          type: "boolean"
    Meaning:
      type: "object"
      required:
        - meaning
      properties:
        id:
          type: "integer"
        meaning:
          type: "string"
        active:
          type: "boolean"
    Reflection:
      type: "object"
      required:
        - reflection
      properties:
        id:
          type: "integer"
        reflection:
          type: "string"
        active:
          type: "boolean"
    User:
      type: "object"
      required:
        - first_name
        - last_name
        - email
        - created_on
        - modified_on
      properties:
        first_name:
          type: "string"
        last_name:
          type: "string"
        created_on:
          type: "string"
        modified_on:
          type: "string"
    Project:
      type: "object"
      required:
        - oroject_name
        - project_owner
        - is_active
        - created_on
        - modified_on
      properties:
        project_name:
          type: "string"
        project_owner:
          type: "string"
        is_active:
          type: "string"
        created_on:
          type: "string"
        modified_on:
          type: "string"

paths:
  /users:
    get:
      operationId: "api.users.get_all"
      tags:
        - "Users"
      summary: "Return the list of users"
      responses:
        "200":
          description: "Successfully read list of users"
  /users/{user_id}:
    get:
      operationId: "api.users.get"
      parameters:
        - name: user_id
          in: path
          description: "ID of user to fetch"
          required: true
          schema:
            type: integer
      tags:
        - "Users"
      summary: "Return an individual user by id"
      responses:
        "200":
          description: "Successfully retrieved user"
  /projects:
    get:
      operationId: "api.projects.get_all"
      tags:
        - "Projects"
      summary: "Return the list of projects"
      responses:
        "200":
          description: "Successfully read list of projects"
  /projects/{project_id}:
    get:
      operationId: "api.projects.get"
      parameters:
        - name: project_id
          in: path
          description: "ID of project to fetch"
          required: true
          schema:
            type: integer
      tags:
        - "Projects"
      summary: "Return an individual project by id"
      responses:
        "200":
          description: "Successfully retrieved project"
  /words:
    get:
      operationId: "api.words.get_all"
      parameters:
        - in: query
          name: filter
          schema:
            type: string
            enum: [all, onlyActive, onlyDeleted]
          required: false
      tags:
        - "Words"
      summary: "Return the list of words"
      responses:
        "200":
          description: "Successfully read list of words"
    post:
      operationId: "api.words.create"
      tags:
        - "Words"
      summary: "Create a new word"
      requestBody:
        description: "Word to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "word"
              $ref: "#/components/schemas/Word"
      responses:
        "200":
          description: "Successfully created word"
  /words/{word_id}:
    get:
      operationId: "api.words.get"
      parameters:
        - name: word_id
          in: path
          description: "ID of word to fetch"
          required: true
          schema:
            type: integer
      tags:
        - "Words"
      summary: "Return an individual word by id"
      responses:
        "200":
          description: "Successfully retrieved word"
    put:
      operationId: "api.words.update"
      tags:
        - "Words"
      summary: "Update an existing word"
      requestBody:
        description: "Word to update"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "word"
              $ref: "#/components/schemas/Word"
      responses:
        "200":
          description: "Successfully updated word"
    delete:
      operationId: "api.words.delete"
      parameters:
        - name: word_id
          in: path
          description: "ID of word to delete"
          required: true
          schema:
            type: integer
      tags:
        - "Words"
      summary: "Delete an individual word by id"
      responses:
        "200":
          description: "Successfully deleted word"

  /words/{word_id}/meanings:
    get:
      operationId: "api.meanings.get_all"
      parameters:
        - name: word_id
          in: path
          description: "ID of word for meanings being fetched"
          required: true
          schema:
            type: integer
        - in: query
          name: filter
          schema:
            type: string
            enum: [all, onlyActive, onlyDeleted]
          required: false
      tags:
        - "Meanings"
      summary: "Return the list of meanings for a word"
      responses:
        "200":
          description: "Successfully read list of meanings"
    post:
      operationId: "api.meanings.create"
      tags:
        - "Meanings"
      summary: "Create a new meaning for a word"
      requestBody:
        description: "Meaning to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "meaning"
              $ref: "#/components/schemas/Meaning"
      responses:
        "200":
          description: "Successfully created meaning for word"
  /words/{word_id}/meanings/{meaning_id}:
    get:
      operationId: "api.meanings.get"
      parameters:
        - name: word_id
          in: path
          description: "ID of word for meanings being fetched"
          required: true
          schema:
            type: integer
        - name: meaning_id
          in: path
          description: "ID of meaning to fetch"
          required: true
          schema:
            type: integer
      tags:
        - "Meanings"
      summary: "Return an individual meaning by id"
      responses:
        "200":
          description: "Successfully retrieved meaning"
    put:
      operationId: "api.meanings.update"
      tags:
        - "Meanings"
      summary: "Update an existing meaning"
      requestBody:
        description: "Meaning to update"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "meaning"
              $ref: "#/components/schemas/Meaning"
      responses:
        "200":
          description: "Successfully updated meaning"
    delete:
      operationId: "api.meanings.delete"
      parameters:
        - name: word_id
          in: path
          description: "ID of word for meaning being deleted"
          required: true
          schema:
            type: integer
        - name: meaning_id
          in: path
          description: "ID of meaning to delete"
          required: true
          schema:
            type: integer
      tags:
        - "Meanings"
      summary: "Delete an individual meaning by id"
      responses:
        "200":
          description: "Successfully deleted meaning"
  /words/{word_id}/reflections:
    get:
      operationId: "api.reflections.get_all"
      parameters:
        - name: word_id
          in: path
          description: "ID of word for reflections being fetched"
          required: true
          schema:
            type: integer
        - in: query
          name: filter
          schema:
            type: string
            enum: [all, onlyActive, onlyDeleted]
          required: false
      tags:
        - "Reflections"
      summary: "Return the list of reflections for a word"
      responses:
        "200":
          description: "Successfully read list of reflections"
    post:
      operationId: "api.reflections.create"
      tags:
        - "Reflections"
      summary: "Create a new reflection for a word"
      requestBody:
        description: "Reflection to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "reflection"
              $ref: "#/components/schemas/Reflection"
      responses:
        "200":
          description: "Successfully created reflection for word"
  /words/{word_id}/reflections/{reflection_id}:
    get:
      operationId: "api.reflections.get"
      parameters:
        - name: word_id
          in: path
          description: "ID of word for reflections being fetched"
          required: true
          schema:
            type: integer
        - name: reflection_id
          in: path
          description: "ID of reflection to fetch"
          required: true
          schema:
            type: integer
      tags:
        - "Reflections"
      summary: "Return an individual reflection by id"
      responses:
        "200":
          description: "Successfully retrieved reflection"
    put:
      operationId: "api.reflections.update"
      tags:
        - "Reflections"
      summary: "Update an existing reflection"
      requestBody:
        description: "Reflection to update"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "reflection"
              $ref: "#/components/schemas/Reflection"
      responses:
        "200":
          description: "Successfully updated reflection"
    delete:
      operationId: "api.reflections.delete"
      parameters:
        - name: word_id
          in: path
          description: "ID of word for reflection being deleted"
          required: true
          schema:
            type: integer
        - name: reflection_id
          in: path
          description: "ID of reflection to delete"
          required: true
          schema:
            type: integer
      tags:
        - "Reflections"
      summary: "Delete an individual reflection by id"
      responses:
        "200":
          description: "Successfully deleted reflection"
